# -*- coding: utf-8 -*-
"""Day_4_Windows.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-mVEsFCltft4Xe3RQ8qFhrSn0-SckNWs
"""

import pandas as pd
import sqlite3

# Create an in-memory SQLite database connection
conn = sqlite3.connect(':memory:')
cursor = conn.cursor()

print("Setup complete. Environment ready.")

# Define a messy, unnormalized dataset (UNF/ONF)
# Issues:
# 1. Non-atomic values (multiple textbooks in one field)
# 2. Redundant data
# 3. Mixed concerns (student, course, instructor info in one table)

data_onf = {
    "Student_ID": [101, 101, 102, 103, 104],

    "Student_Name": [
        "Alice",
        "Alice",
        "Bob",
        "Charlie",
        "David"
    ],

    "Course_Code": [
        "CS101",
        "MATH201",
        "CS101",
        "CS102",
        "MATH201"
    ],

    "Course_Name": [
        "Intro to CS",
        "Calculus I",
        "Intro to CS",
        "Data Structures",
        "Calculus I"
    ],

    "Instructor_ID": [
        "INS_01",
        "INS_02",
        "INS_01",
        "INS_03",
        "INS_02"
    ],

    "Instructor_Name": [
        "Dr. Smith",
        "Dr. Jones",
        "Dr. Smith",
        "Dr. Alan",
        "Dr. Jones"
    ],

    "Instructor_Office": [
        "Room 401",
        "Room 502",
        "Room 401",
        "Room 403",
        "Room 502"
    ],

    "Textbooks_Required": [
        "Python Basics, Intro to CLI",
        "Calculus Vol 1",
        "Python Basics, Intro to CLI",
        "Data Structures in Python",
        "Calculus Vol 1"
    ],

    "Grade": [
        "A",
        "B",
        "A",
        "B+",
        "A-"
    ]
}

# Create DataFrame
df_onf = pd.DataFrame(data_onf)

# Store in SQLite
df_onf.to_sql(
    'Unnormalized_Student_Data',
    conn,
    index=False,
    if_exists='replace'
)

print("\n--- Unnormalized Data (UNF/ONF) ---")
print(df_onf)

# Convert ONF -> 1NF

df_1nf = df_onf.copy()

# Split textbooks into a list
df_1nf["Textbooks_Required"] = (
    df_1nf["Textbooks_Required"]
    .str.split(", ")
)

# Create a separate row for each textbook
df_1nf = df_1nf.explode("Textbooks_Required")

# Reset index
df_1nf = df_1nf.reset_index(drop=True)

# Store in SQLite
df_1nf.to_sql(
    "Student_Data_1NF",
    conn,
    index=False,
    if_exists="replace"
)

print("\n--- First Normal Form (1NF) ---")
print(df_1nf)

#2nf
students = df_1nf[
    ["Student_ID", "Student_Name"]
].drop_duplicates()

students.to_sql(
    "Students_2NF",
    conn,
    index=False,
    if_exists="replace"
)

print("\n--- Students Table (2NF) ---")
print(students)

#3nf
students_3nf = df_1nf[
    ["Student_ID", "Student_Name"]
].drop_duplicates()

students_3nf.to_sql(
    "Students_3NF",
    conn,
    index=False,
    if_exists="replace"
)

# RUN THIS CELL TO SETUP THE CHALLENGE DATA
#Task 1 Day_4

import pandas as pd
import sqlite3

# Create in-memory SQLite database
conn_challenge = sqlite3.connect(':memory:')

challenge_data = {
    "Visit_ID": [5001, 5001, 5002, 5003],
    "Student_ID": [101, 101, 102, 104],
    "Student_Name": ["Alice", "Alice", "Bob", "David"],
    "Doctor_ID": ["DOC_XYZ", "DOC_XYZ", "DOC_ABC", "DOC_XYZ"],
    "Doctor_Name": ["Dr. Evans", "Dr. Evans", "Dr. Green", "Dr. Evans"],
    "Doctor_Clinic": ["General Medicine", "General Medicine", "Sports Med", "General Medicine"],
    "Prescriptions": ["Amoxicillin, Ibuprofen", "Amoxicillin, Ibuprofen", "Bandages", "Vitamin D"]
}

# Create DataFrame
df_challenge = pd.DataFrame(challenge_data)

# Save to SQLite table
df_challenge.to_sql(
    'Patient_Visits_ONF',
    conn_challenge,
    index=False,
    if_exists='replace'
)

print("--- Challenge Dataset (ONF) ---")
print(df_challenge)

#Task2
# Normalize to 1NF

df_1nf = df_challenge.copy()

# Split multiple prescriptions into lists
df_1nf['Prescriptions'] = df_1nf['Prescriptions'].str.split(',')

# Create one row per prescription
df_1nf = df_1nf.explode('Prescriptions')

# Remove extra spaces
df_1nf['Prescriptions'] = df_1nf['Prescriptions'].str.strip()

print("--- 1NF Table ---")
print(df_1nf)
"""
1. Why does the table violate 1NF?

Prescriptions contains multiple values in one cell (Amoxicillin, Ibuprofen).
1NF requires atomic values.

2. Why do Student_Name and Doctor_Clinic violate higher normal forms?

Student_ID → Student_Name
Doctor_ID → Doctor_Clinic
These attributes depend on other non-key attributes rather than directly on Visit_ID.

3. Which normal form is violated if Doctor_ID determines Doctor_Clinic?

3NF is violated because of the transitive dependency:
Visit_ID → Doctor_ID → Doctor_Clinic
"""

import pandas as pd
import sqlite3

# Create in-memory database
conn = sqlite3.connect(':memory:')

# Server inventory table
servers_inventory = {
    "Host_ID": ["SRV-01", "SRV-02", "SRV-03"],
    "Role": ["Web Front", "API Gateway", "Database Replica"]
}

# Network interfaces table
live_interfaces = {
    "Interface_ID": ["eth0", "eth1"],
    "Mapped_Host": ["SRV-01", "SRV-02"],
    "IP_Address": ["10.0.0.4", "10.0.0.9"]
}

# Create DataFrames
df_srv = pd.DataFrame(servers_inventory)
df_inf = pd.DataFrame(live_interfaces)

# Store in SQLite
df_srv.to_sql('Servers', conn, index=False, if_exists='replace')
df_inf.to_sql('Interfaces', conn, index=False, if_exists='replace')

# Faulty Query Fixed
faulty_query = """
SELECT s.Host_ID,
       s.Role,
       i.Interface_ID,
       i.IP_Address
FROM Servers s
INNER JOIN Interfaces i
ON s.Host_ID = i.Mapped_Host;
"""

print("--- Faulty Output Metrics (Missing Database Replica SRV-03) ---")

result = pd.read_sql_query(faulty_query, conn)
print(result)

"""
Rewrite the query below to implement a join strategy that outputs all server configurations from inventory, regardless of whether they have a live network interface.
"""

query = """
SELECT
    s.Host_ID,
    s.Role,
    i.Interface_ID,
    i.IP_Address
FROM Servers s
LEFT JOIN Interfaces i
    ON s.Host_ID = i.Mapped_Host;
"""

result = pd.read_sql_query(query, conn)

print(result)