# -*- coding: utf-8 -*-
"""Evalutaion_Metrics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LmqrqEmrzSp6CUUizMyx9X4YVpd2mK6f
"""

from sentence_transformers import SentenceTransformer, util

model = SentenceTransformer("all-MiniLM-L6-v2")

def factscore(answer, retrieved_docs):
    sentences = answer.split(".")
    scores = []

    doc_embedding = model.encode(" ".join(retrieved_docs), convert_to_tensor=True)

    for s in sentences:
        if len(s.strip()) == 0:
            continue

        sent_embedding = model.encode(s, convert_to_tensor=True)
        sim = util.pytorch_cos_sim(sent_embedding, doc_embedding).item()

        scores.append(sim)

    return sum(scores) / len(scores) if scores else 0

!pip install -q sentence-transformers bert-score scikit-learn

from sentence_transformers import SentenceTransformer, util
from bert_score import score
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
model = SentenceTransformer("all-MiniLM-L6-v2")

def factscore(answer, retrieved_docs):
    sentences = [s.strip() for s in answer.split(".") if s.strip()]
    doc_text = " ".join(retrieved_docs)

    doc_emb = model.encode(doc_text, convert_to_tensor=True)

    scores = []
    for s in sentences:
        sent_emb = model.encode(s, convert_to_tensor=True)
        sim = util.pytorch_cos_sim(sent_emb, doc_emb).item()
        scores.append(sim)

    return float(np.mean(scores)) if scores else 0

def hhem_score(answer, context):
    a_tokens = set(answer.lower().split())
    c_tokens = set(context.lower().split())

    overlap = len(a_tokens & c_tokens)
    return overlap / len(a_tokens) if a_tokens else 0

def bertscore_eval(pred, reference):
    P, R, F1 = score([pred], [reference], lang="en")

    return {
        "precision": float(P.mean()),
        "recall": float(R.mean()),
        "f1": float(F1.mean())
    }

def selfcheckgpt(samples):
    embeddings = model.encode(samples)

    sims = []
    for i in range(len(samples)):
        for j in range(i + 1, len(samples)):
            sim = cosine_similarity(
                [embeddings[i]], [embeddings[j]]
            )[0][0]
            sims.append(sim)

    return float(np.mean(sims)) if sims else 0

def groundedness(answer, retrieved_chunks):
    a_tokens = set(answer.lower().split())
    c_tokens = set(" ".join(retrieved_chunks).lower().split())

    overlap = a_tokens & c_tokens

    return len(overlap) / len(a_tokens) if a_tokens else 0

def evaluate_all(answer, reference, context, retrieved_docs, samples):
    return {
        "FactScore": factscore(answer, retrieved_docs),
        "HHEM": hhem_score(answer, context),
        "BERTScore": bertscore_eval(answer, reference),
        "SelfCheckGPT": selfcheckgpt(samples),
        "Groundedness": groundedness(answer, retrieved_docs)
    }

answer = "The capital of India is New Delhi. It is located in the north."
reference = "New Delhi is the capital of India."
context = "Karnataka capital city is bangalore in India."
retrieved_docs = [
    "New Delhi is the capital of India",
    "It is located in northern India"
]
samples = [
    "New Delhi is the capital of India",
    "India's capital is New Delhi",
    "The capital city of India is Delhi"
]

result = evaluate_all(answer, reference, context, retrieved_docs, samples)

result

