# -*- coding: utf-8 -*-
"""RAG_Homework.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b1jL93BTx3agvWOoEWmjISEuU7QSuBCN
"""

!pip install groq pandas

from getpass import getpass

GROQ_API_KEY = getpass("Enter Groq API Key: ")

from groq import Groq

client = Groq(api_key=GROQ_API_KEY)

samples = [
    {
        "question": "What is RAG?",
        "context": """
        Retrieval Augmented Generation (RAG)
        combines document retrieval and LLMs.
        Retrieved documents are supplied to the model
        before generating an answer.
        """,
        "answer": """
        RAG retrieves relevant documents and uses
        them while generating answers.
        """
    },

    {
        "question": "Who founded Microsoft?",
        "context": """
        Microsoft was founded by Bill Gates and
        Paul Allen in 1975.
        """,
        "answer": """
        Microsoft was founded by Steve Jobs.
        """
    }
]

#generic Evalution
def evaluate(prompt):

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {
                "role": "user",
                "content": prompt
            }
        ],
        temperature=0
    )

    return response.choices[0].message.content

#Context Relevence
def context_relevance(question, context):

    prompt = f"""
You are an evaluator.

Question:
{question}

Context:
{context}

Rate context relevance from 1-5.

Return:
Score:
Reason:
"""

    return evaluate(prompt)

#Answer Relevence
def answer_relevance(question, answer):

    prompt = f"""
Question:
{question}

Answer:
{answer}

Rate answer relevance from 1-5.

Return:
Score:
Reason:
"""

    return evaluate(prompt)

#Groundness
def groundedness(context, answer):

    prompt = f"""
Context:
{context}

Answer:
{answer}

Determine whether answer is fully supported
by the context.

Score 1-5.

Return:
Score:
Reason:
"""

    return evaluate(prompt)

for sample in samples:

    print("\nQUESTION")
    print(sample["question"])

    print("\nCONTEXT RELEVANCE")
    print(
        context_relevance(
            sample["question"],
            sample["context"]
        )
    )

    print("\nANSWER RELEVANCE")
    print(
        answer_relevance(
            sample["question"],
            sample["answer"]
        )
    )

    print("\nGROUNDEDNESS")
    print(
        groundedness(
            sample["context"],
            sample["answer"]
        )
    )

    print("\n" + "="*80)