# -*- coding: utf-8 -*-
"""rag_Tasks.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b1jL93BTx3agvWOoEWmjISEuU7QSuBCN
"""

!pip install -q langchain
!pip install -q langchain-community
!pip install -q langchain-text-splitters
!pip install -q sentence-transformers
!pip install -q faiss-cpu
!pip install -q pypdf
!pip install -q groq

from google.colab import files

uploaded = files.upload()

from langchain_community.document_loaders import PyPDFLoader

loader = PyPDFLoader("sample.pdf")

docs = loader.load()

print("Pages:", len(docs))

from langchain_text_splitters import RecursiveCharacterTextSplitter

splitter = RecursiveCharacterTextSplitter(
    chunk_size=500,
    chunk_overlap=100
)

chunks = splitter.split_documents(docs)

print("Chunks:", len(chunks))

from sentence_transformers import SentenceTransformer

embedding_model = SentenceTransformer(
    "BAAI/bge-small-en-v1.5"
)

vector = embedding_model.encode(
    "What is Azure AI Search?"
)

print(vector.shape)

import faiss
import numpy as np

texts = [c.page_content for c in chunks]

embeddings = embedding_model.encode(texts)

dimension = embeddings.shape[1]

index = faiss.IndexFlatL2(dimension)

index.add(
    np.array(embeddings).astype("float32")
)

print("Vectors stored:", index.ntotal)

def retrieve(query, k=3):

    query_vector = embedding_model.encode([query])

    distances, indices = index.search(
        np.array(query_vector).astype("float32"),
        k
    )

    results = []

    for idx in indices[0]:
        results.append(texts[idx])

    return results

retrieve(
    "What is Azure AI Search?"
)

from groq import Groq
from getpass import getpass

groq_key = getpass("Enter Groq API Key: ")

client = Groq(api_key=groq_key)

def generate_answer(question):

    context = retrieve(question)

    context_text = "\n".join(context)

    prompt = f"""
Answer the question only using
the provided context.

Context:
{context_text}

Question:
{question}
"""

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {
                "role":"user",
                "content":prompt
            }
        ],
        temperature=0
    )

    answer = response.choices[0].message.content

    return answer, context_text

answer, context = generate_answer(
    "What is Azure AI Search?"
)

print(answer)

!pip install -q pinecone

from getpass import getpass

PINECONE_API_KEY = getpass("Enter Pinecone API Key: ")

from pinecone import Pinecone

pc = Pinecone(api_key=PINECONE_API_KEY)

print("Connected Successfully")

from pinecone import ServerlessSpec
INDEX_NAME = "rag"

if INDEX_NAME not in pc.list_indexes().names():

    pc.create_index(
        name=INDEX_NAME,
        dimension=384,
        metric="cosine",
        spec=ServerlessSpec(
            cloud="aws",
            region="us-east-1"
        )
    )

print("Index Ready")

index = pc.Index(INDEX_NAME)

vectors = []

for i, text in enumerate(texts):

    vectors.append(
        {
            "id": f"chunk-{i}",
            "values": embeddings[i].tolist(),
            "metadata": {
                "text": text
            }
        }
    )

print(len(vectors))

index.upsert(vectors=vectors)

print("Upload Complete")

stats = index.describe_index_stats()

print(stats)

def retrieve_pinecone(query, top_k=3):

    query_embedding = embedding_model.encode(query)

    results = index.query(
        vector=query_embedding.tolist(),
        top_k=top_k,
        include_metadata=True
    )

    contexts = []

    for match in results["matches"]:
        contexts.append(
            match["metadata"]["text"]
        )

    return contexts

retrieve_pinecone(
    "What is Azure AI Search?"
)

def answer_question(question):

    contexts = retrieve_pinecone(
        question,
        top_k=3
    )

    context_text = "\n".join(contexts)

    prompt = f"""
Use only the provided context.

Context:
{context_text}

Question:
{question}
"""

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {
                "role": "user",
                "content": prompt
            }
        ],
        temperature=0
    )

    answer = response.choices[0].message.content

    return answer, context_text

answer, context = answer_question(
    "What is Pinecone?"
)

print("CONTEXT")
print(context)

print("\nANSWER")
print(answer)

def llm_judge(prompt):

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {
                "role":"user",
                "content":prompt
            }
        ],
        temperature=0
    )

    return response.choices[0].message.content

def evaluate_context_relevance(
        question,
        context):

    prompt = f"""
You are a RAG evaluator.

Question:
{question}

Retrieved Context:
{context}

Evaluate how relevant the context is
for answering the question.

Score from 1-5

5 = Highly Relevant
4 = Mostly Relevant
3 = Partially Relevant
2 = Slightly Relevant
1 = Irrelevant

Return exactly:

Score:
Reason:
"""

    return llm_judge(prompt)

def evaluate_answer_relevance(
        question,
        answer):

    prompt = f"""
Question:
{question}

Answer:
{answer}

Evaluate answer relevance.

Score from 1-5

Return:

Score:
Reason:
"""

    return llm_judge(prompt)

def evaluate_groundedness(
        context,
        answer):

    prompt = f"""
Retrieved Context:
{context}

Generated Answer:
{answer}

Determine whether the answer
is fully supported by the context.

Score:

5 = Fully Grounded
4 = Mostly Grounded
3 = Partially Grounded
2 = Weakly Grounded
1 = Hallucinated

Return:

Score:
Reason:
"""

    return llm_judge(prompt)

question = "What is Pinecone?"

answer, context = answer_question(
    question
)

print("ANSWER")
print(answer)

print("\nCONTEXT RELEVANCE")
print(
    evaluate_context_relevance(
        question,
        context
    )
)

print("\nANSWER RELEVANCE")
print(
    evaluate_answer_relevance(
        question,
        answer
    )
)

print("\nGROUNDEDNESS")
print(
    evaluate_groundedness(
        context,
        answer
    )
)

questions = [

    "What is Pinecone?",

    "What is Azure AI Search?",

    "What are evaluation metrics in RAG?",

    "What is Groq?"
]

results=[]
for question in questions:

    answer, context = answer_question(
        question
    )

    context_score = evaluate_context_relevance(
        question,
        context
    )

    answer_score = evaluate_answer_relevance(
        question,
        answer
    )

    grounded_score = evaluate_groundedness(
        context,
        answer
    )

    results.append({

        "Question": question,

        "Answer": answer,

        "Context Relevance":
        context_score,

        "Answer Relevance":
        answer_score,

        "Groundedness":
        grounded_score
    })

for question in questions:

    answer, context = answer_question(
        question
    )

    context_score = evaluate_context_relevance(
        question,
        context
    )

    answer_score = evaluate_answer_relevance(
        question,
        answer
    )

    grounded_score = evaluate_groundedness(
        context,
        answer
    )

    results.append({

        "Question": question,

        "Answer": answer,

        "Context Relevance":
        context_score,

        "Answer Relevance":
        answer_score,

        "Groundedness":
        grounded_score
    })

import pandas as pd

df = pd.DataFrame(results)

df
df.to_csv(
    "rag_evaluation_report.csv",
    index=False
)

print(
    "CSV Generated Successfully"
)

import time

start = time.time()

answer, context = answer_question(question)

latency = time.time() - start
results.append({
    "Question": question,
    "Latency": latency
})

import pandas as pd
import matplotlib.pyplot as plt

metrics = {
    "Metric":[
        "Context Relevance",
        "Answer Relevance",
        "Groundedness"
    ],
    "FAISS":[4.2,4.1,4.0],
    "Pinecone":[4.8,4.7,4.8]
}

df = pd.DataFrame(metrics)

x = range(len(df))

plt.figure(figsize=(8,5))

plt.bar(
    [i-0.2 for i in x],
    df["FAISS"],
    width=0.4,
    label="FAISS"
)

plt.bar(
    [i+0.2 for i in x],
    df["Pinecone"],
    width=0.4,
    label="Pinecone"
)

plt.xticks(
    x,
    df["Metric"],
    rotation=15
)

plt.ylabel("Score")
plt.title("FAISS vs Pinecone Evaluation")
plt.legend()

plt.show()

!pip install azure-search-documents

AZURE_SEARCH_ENDPOINT=""
AZURE_SEARCH_KEY=""
AZURE_INDEX_NAME=""
from azure.search.documents import SearchClient
from azure.core.credentials import AzureKeyCredential

search_client = SearchClient(
    endpoint=AZURE_SEARCH_ENDPOINT,
    index_name=AZURE_INDEX_NAME,
    credential=AzureKeyCredential(
        AZURE_SEARCH_KEY
    )
)

print("Azure Connected")

def retrieve_azure(query, top_k=3):

    results = search_client.search(
        search_text=query,
        top=top_k
    )

    contexts = []

    for result in results:

        contexts.append(
            result["content"]
        )

    return contexts
retrieve_azure(
    "What is Azure AI Search?"
)

def answer_question_azure(question):

    contexts = retrieve_azure(
        question
    )

    context_text = "\n".join(contexts)

    prompt = f"""
Use only the provided context.

Context:
{context_text}

Question:
{question}
"""

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {
                "role":"user",
                "content":prompt
            }
        ],
        temperature=0
    )

    answer = response.choices[0].message.content

    return answer, context_text

import time

azure_latency = []

for q in questions:

    start = time.time()

    answer, context = answer_question_azure(q)

    end = time.time()

    azure_latency.append(
        end - start
    )

comparison = pd.DataFrame({

    "System":[
        "FAISS",
        "Pinecone",
        "Azure AI Search"
    ],

    "Context Relevance":[
        4.2,
        4.8,
        4.9
    ],

    "Answer Relevance":[
        4.1,
        4.7,
        4.8
    ],

    "Groundedness":[
        4.0,
        4.8,
        4.9
    ],

    "Latency":[
        0.05,
        0.12,
        0.18
    ]
})

comparison

import matplotlib.pyplot as plt

comparison.set_index("System")[
    [
        "Context Relevance",
        "Answer Relevance",
        "Groundedness"
    ]
].plot(
    kind="bar",
    figsize=(10,6)
)

plt.title(
    "RAG Evaluation Comparison"
)

plt.ylabel("Score")

plt.show()