# from app.config.settings import OPENAI_API_KEY
# from app.config.settings import OPENAI_MODEL





# app/agents/diagnosis_agent.py

import json
import logging
from pathlib import Path
from datetime import datetime

import psutil
import requests


class DiagnosisAgent:

    def __init__(
        self,
        incident_log="logs/incident.log",
        diagnosis_log="logs/diagnosis.log"
    ):
        self.incident_log = Path(incident_log)
        self.diagnosis_log = Path(diagnosis_log)

        logging.basicConfig(
            level=logging.INFO,
            format="%(asctime)s - %(levelname)s - %(message)s"
        )

    # ----------------------------------------------------
    # Read latest incident generated by Monitoring Agent
    # ----------------------------------------------------
    def read_latest_incident(self):

        if not self.incident_log.exists():
            return None

        with open(self.incident_log, "r") as f:
            lines = f.readlines()

        if not lines:
            return None

        return json.loads(lines[-1])

    # ----------------------------------------------------
    # Collect system metrics
    # ----------------------------------------------------
    def collect_system_metrics(self):

        metrics = {
            "cpu": psutil.cpu_percent(interval=1),
            "memory": psutil.virtual_memory().percent,
            "disk": psutil.disk_usage("/").percent,
        }

        return metrics

    # ----------------------------------------------------
    # Check internet connectivity
    # ----------------------------------------------------
    def check_network(self):

        try:
            requests.get(
                "https://www.google.com",
                timeout=3
            )
            return True

        except Exception:
            return False

    # ----------------------------------------------------
    # Root Cause Analysis
    # ----------------------------------------------------
    def analyze(self, incident):

        metrics = self.collect_system_metrics()
        network = self.check_network()

        status_code = incident.get("status_code")
        error = str(incident.get("error", "")).lower()

        root_cause = "Unknown"
        recommendation = "Manual Investigation"
        healable = False
        confidence = "Low"

        # ---------- System Level ----------

        if metrics["cpu"] > 90:

            root_cause = "High CPU Usage"
            recommendation = "Restart Service"
            healable = True
            confidence = "High"

        elif metrics["memory"] > 90:

            root_cause = "High Memory Usage"
            recommendation = "Restart Application"
            healable = True
            confidence = "High"

        elif metrics["disk"] > 95:

            root_cause = "Disk Full"
            recommendation = "Clean Disk"
            healable = False
            confidence = "High"

        elif not network:

            root_cause = "Network Connectivity Issue"
            recommendation = "Check Internet Connection"
            healable = True
            confidence = "High"

        # ---------- HTTP Status ----------

        elif status_code == 503:

            root_cause = "Weather API Service Unavailable"
            recommendation = "Retry API"
            healable = True
            confidence = "High"

        elif status_code == 500:

            root_cause = "Internal Server Error"
            recommendation = "Retry API"
            healable = True
            confidence = "High"

        elif status_code == 404:

            root_cause = "Invalid Endpoint"
            recommendation = "Verify URL"
            healable = False
            confidence = "High"

        elif status_code == 401:

            root_cause = "Authentication Failure"
            recommendation = "Check API Key"
            healable = False
            confidence = "High"

        elif status_code == 429:

            root_cause = "Rate Limit Exceeded"
            recommendation = "Retry After Delay"
            healable = True
            confidence = "High"

        # ---------- Exception ----------

        elif "timeout" in error:

            root_cause = "Request Timeout"
            recommendation = "Increase Timeout / Retry"
            healable = True
            confidence = "High"

        elif "connection" in error:

            root_cause = "Connection Error"
            recommendation = "Retry Connection"
            healable = True
            confidence = "High"

        diagnosis = {

            "timestamp": datetime.now().isoformat(),
            "city": incident.get("city"),  

            "service": incident.get("service"),

            "status": incident.get("status"),
            "failure_mode": incident.get("failure_mode"),

            "status_code": status_code,

            "cpu": metrics["cpu"],

            "memory": metrics["memory"],

            "disk": metrics["disk"],

            "network": network,

            "root_cause": root_cause,

            "confidence": confidence,

            "healable": healable,

            "recommended_action": recommendation
        }

        return diagnosis

    # ----------------------------------------------------
    # Save Diagnosis
    # ----------------------------------------------------
    def save_diagnosis(self, diagnosis):

        self.diagnosis_log.parent.mkdir(
            parents=True,
            exist_ok=True
        )

        with open(self.diagnosis_log, "a") as f:
            f.write(json.dumps(diagnosis) + "\n")

        logging.info("Diagnosis saved.")

    # ----------------------------------------------------
    # Main Entry
    # ----------------------------------------------------
    def run(self):

        incident = self.read_latest_incident()

        if incident is None:
            logging.warning("No incident found.")
            return None

        diagnosis = self.analyze(incident)

        self.save_diagnosis(diagnosis)

        return diagnosis


if __name__ == "__main__":

    agent = DiagnosisAgent()

    result = agent.run()

    print(json.dumps(result, indent=4))